"""add_detailed_timing_columns_to_heartbeats

Revision ID: 14802c64e2f7
Revises: 081b80ecae31
Create Date: 2026-03-25 10:28:52.892753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14802c64e2f7'
down_revision: Union[str, Sequence[str], None] = '081b80ecae31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heartbeats', sa.Column('tcp_connect_ms', sa.Float(), nullable=True))
    op.add_column('heartbeats', sa.Column('tls_handshake_ms', sa.Float(), nullable=True))
    op.add_column('heartbeats', sa.Column('ttfb_ms', sa.Float(), nullable=True))
    op.add_column('heartbeats', sa.Column('timing_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heartbeats', 'timing_details')
    op.drop_column('heartbeats', 'ttfb_ms')
    op.drop_column('heartbeats', 'tls_handshake_ms')
    op.drop_column('heartbeats', 'tcp_connect_ms')
    # ### end Alembic commands ###
