"""add_admin_and_blocked_emails

Revision ID: 4834295acc04
Revises: f7beabb5404f
Create Date: 2026-04-08 11:18:02.353729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4834295acc04'
down_revision: Union[str, Sequence[str], None] = 'f7beabb5404f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_page_components_status_page_id'), table_name='status_page_components')
    op.drop_table('status_page_components')
    op.drop_index(op.f('ix_incident_components_component_id'), table_name='incident_components')
    op.drop_index(op.f('ix_incident_components_incident_id'), table_name='incident_components')
    op.drop_table('incident_components')
    op.drop_index(op.f('ix_status_pages_slug'), table_name='status_pages')
    op.drop_index(op.f('ix_status_pages_user_id'), table_name='status_pages')
    op.drop_table('status_pages')
    op.drop_index(op.f('ix_incident_heartbeats_heartbeat_id'), table_name='incident_heartbeats')
    op.drop_index(op.f('ix_incident_heartbeats_incident_id'), table_name='incident_heartbeats')
    op.drop_table('incident_heartbeats')
    op.drop_index(op.f('ix_status_page_subscribers_email'), table_name='status_page_subscribers')
    op.drop_index(op.f('ix_status_page_subscribers_status_page_id'), table_name='status_page_subscribers')
    op.drop_table('status_page_subscribers')
    op.drop_index(op.f('ix_monitor_incidents_monitor_id'), table_name='monitor_incidents')
    op.drop_index(op.f('ix_monitor_incidents_started_at'), table_name='monitor_incidents')
    op.drop_index(op.f('ix_monitor_incidents_status'), table_name='monitor_incidents')
    op.drop_table('monitor_incidents')
    op.drop_index(op.f('ix_incident_updates_created_at'), table_name='incident_updates')
    op.drop_index(op.f('ix_incident_updates_incident_id'), table_name='incident_updates')
    op.drop_table('incident_updates')
    op.drop_index(op.f('ix_incidents_started_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status_page_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_scheduled_maintenances_scheduled_start'), table_name='scheduled_maintenances')
    op.drop_index(op.f('ix_scheduled_maintenances_status_page_id'), table_name='scheduled_maintenances')
    op.drop_table('scheduled_maintenances')
    op.drop_index(op.f('ix_maintenance_components_component_id'), table_name='maintenance_components')
    op.drop_index(op.f('ix_maintenance_components_maintenance_id'), table_name='maintenance_components')
    op.drop_table('maintenance_components')
    op.drop_index(op.f('ix_component_monitors_component_id'), table_name='component_monitors')
    op.drop_index(op.f('ix_component_monitors_monitor_id'), table_name='component_monitors')
    op.drop_table('component_monitors')
    op.drop_index(op.f('ix_heartbeats_incident_id'), table_name='heartbeats')
    op.drop_constraint(op.f('fk_heartbeats_incident_id'), 'heartbeats', type_='foreignkey')
    op.drop_column('heartbeats', 'ssl_error_details')
    op.drop_column('heartbeats', 'response_headers')
    op.drop_column('heartbeats', 'dns_lookup_ms')
    op.drop_column('heartbeats', 'incident_id')
    op.drop_column('heartbeats', 'error_type')
    op.drop_column('monitors', 'maintenance_until')
    op.drop_constraint(op.f('user_notification_settings_user_id_key'), 'user_notification_settings', type_='unique')
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=True)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_notification_settings_user_id_key'), 'user_notification_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.add_column('monitors', sa.Column('maintenance_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('dns_lookup_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('ssl_error_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_heartbeats_incident_id'), 'heartbeats', 'monitor_incidents', ['incident_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_heartbeats_incident_id'), 'heartbeats', ['incident_id'], unique=False)
    op.create_table('component_monitors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['status_page_components.id'], name=op.f('component_monitors_component_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('component_monitors_monitor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('component_monitors_pkey')),
    sa.UniqueConstraint('component_id', 'monitor_id', name=op.f('uq_component_monitor'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_component_monitors_monitor_id'), 'component_monitors', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_component_monitors_component_id'), 'component_monitors', ['component_id'], unique=False)
    op.create_table('maintenance_components',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('maintenance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['status_page_components.id'], name=op.f('maintenance_components_component_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['scheduled_maintenances.id'], name=op.f('maintenance_components_maintenance_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_components_pkey')),
    sa.UniqueConstraint('maintenance_id', 'component_id', name=op.f('uq_maintenance_component'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_maintenance_components_maintenance_id'), 'maintenance_components', ['maintenance_id'], unique=False)
    op.create_index(op.f('ix_maintenance_components_component_id'), 'maintenance_components', ['component_id'], unique=False)
    op.create_table('scheduled_maintenances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scheduled_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('scheduled_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actual_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('actual_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('scheduled_maintenances_created_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_page_id'], ['status_pages.id'], name=op.f('scheduled_maintenances_status_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_maintenances_pkey'))
    )
    op.create_index(op.f('ix_scheduled_maintenances_status_page_id'), 'scheduled_maintenances', ['status_page_id'], unique=False)
    op.create_index(op.f('ix_scheduled_maintenances_scheduled_start'), 'scheduled_maintenances', ['scheduled_start'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('incidents_created_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_page_id'], ['status_pages.id'], name=op.f('incidents_status_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_index(op.f('ix_incidents_status_page_id'), 'incidents', ['status_page_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_started_at'), 'incidents', ['started_at'], unique=False)
    op.create_table('incident_updates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('incident_updates_created_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_updates_incident_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_updates_pkey'))
    )
    op.create_index(op.f('ix_incident_updates_incident_id'), 'incident_updates', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_updates_created_at'), 'incident_updates', ['created_at'], unique=False)
    op.create_table('monitor_incidents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_downtime_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('affected_checks_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('root_cause_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('root_cause_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_patterns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_auto_created', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_pushed_to_status_page', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('status_page_incident_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('monitor_incidents_monitor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_page_incident_id'], ['incidents.id'], name=op.f('monitor_incidents_status_page_incident_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('monitor_incidents_pkey'))
    )
    op.create_index(op.f('ix_monitor_incidents_status'), 'monitor_incidents', ['status'], unique=False)
    op.create_index(op.f('ix_monitor_incidents_started_at'), 'monitor_incidents', ['started_at'], unique=False)
    op.create_index(op.f('ix_monitor_incidents_monitor_id'), 'monitor_incidents', ['monitor_id'], unique=False)
    op.create_table('status_page_subscribers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verification_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('unsubscribe_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('subscribed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['status_page_id'], ['status_pages.id'], name=op.f('status_page_subscribers_status_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('status_page_subscribers_pkey')),
    sa.UniqueConstraint('status_page_id', 'email', name=op.f('uq_status_page_subscriber'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_status_page_subscribers_status_page_id'), 'status_page_subscribers', ['status_page_id'], unique=False)
    op.create_index(op.f('ix_status_page_subscribers_email'), 'status_page_subscribers', ['email'], unique=False)
    op.create_table('incident_heartbeats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('heartbeat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['heartbeat_id'], ['heartbeats.id'], name=op.f('incident_heartbeats_heartbeat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['monitor_incidents.id'], name=op.f('incident_heartbeats_incident_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_heartbeats_pkey'))
    )
    op.create_index(op.f('ix_incident_heartbeats_incident_id'), 'incident_heartbeats', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_heartbeats_heartbeat_id'), 'incident_heartbeats', ['heartbeat_id'], unique=False)
    op.create_table('status_pages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('show_uptime', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('show_incident_history', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('branding_logo_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('branding_primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('branding_custom_css', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('template', sa.VARCHAR(length=50), server_default=sa.text("'minimal'::character varying"), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=50), server_default=sa.text("'dark'::character varying"), autoincrement=False, nullable=False),
    sa.Column('layout', sa.VARCHAR(length=50), server_default=sa.text("'list'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('status_pages_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('status_pages_pkey')),
    sa.UniqueConstraint('slug', name=op.f('status_pages_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_status_pages_user_id'), 'status_pages', ['user_id'], unique=False)
    op.create_index(op.f('ix_status_pages_slug'), 'status_pages', ['slug'], unique=False)
    op.create_table('incident_components',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['status_page_components.id'], name=op.f('incident_components_component_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incident_components_incident_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_components_pkey')),
    sa.UniqueConstraint('incident_id', 'component_id', name=op.f('uq_incident_component'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_incident_components_incident_id'), 'incident_components', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_components_component_id'), 'incident_components', ['component_id'], unique=False)
    op.create_table('status_page_components',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['status_page_id'], ['status_pages.id'], name=op.f('status_page_components_status_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('status_page_components_pkey'))
    )
    op.create_index(op.f('ix_status_page_components_status_page_id'), 'status_page_components', ['status_page_id'], unique=False)
    # ### end Alembic commands ###
