// This file is auto-generated by @hey-api/openapi-ts

import { type ClientOptions, type Config, createClient, createConfig } from './client';
import type { ClientOptions as ClientOptions2 } from './types.gen';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends ClientOptions = ClientOptions2> = (override?: Config<ClientOptions & T>) => Config<Required<ClientOptions> & T>;

// Must match @/lib/constants (next.config sets NEXT_PUBLIC_BFF on Vercel for BFF).
const getApiBaseUrl = () => {
  if (process.env.NEXT_PUBLIC_BFF === "1") {
    return "/api/v1";
  }
  return process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
};

export const client = createClient(createConfig<ClientOptions2>({ 
  baseUrl: getApiBaseUrl(),
  credentials: 'include',
  headers: {
    'Content-Type': 'application/json',
  },
}));
