// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ComponentCreate
 */
export type ComponentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Order
     */
    order?: number;
    /**
     * Monitor Ids
     */
    monitor_ids?: Array<string>;
};

/**
 * ComponentResponse
 */
export type ComponentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status Page Id
     */
    status_page_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Order
     */
    order: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Monitors
     */
    monitors?: Array<MonitorSummary>;
    /**
     * Current Status
     */
    current_status?: string;
};

/**
 * ComponentSummary
 */
export type ComponentSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ComponentUpdate
 */
export type ComponentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Order
     */
    order?: number | null;
    /**
     * Monitor Ids
     */
    monitor_ids?: Array<string> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeartbeatMonitorCreate
 *
 * Request model for creating heartbeat monitor
 */
export type HeartbeatMonitorCreate = {
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Interval Seconds
     *
     * How often heartbeat is expected (minimum 60 seconds)
     */
    interval_seconds: number;
    /**
     * Monitor Type
     *
     * Monitor type (must be heartbeat)
     */
    monitor_type?: 'heartbeat';
};

/**
 * HeartbeatReceiveResponse
 *
 * Response when heartbeat ping is received
 */
export type HeartbeatReceiveResponse = {
    /**
     * Success
     *
     * Whether the heartbeat was successfully received
     */
    success: boolean;
    /**
     * Message
     *
     * Human-readable message about the heartbeat reception
     */
    message: string;
    /**
     * Monitor Id
     *
     * ID of the monitor that received the heartbeat
     */
    monitor_id: string;
    /**
     * Received At
     *
     * Timestamp when the heartbeat was received
     */
    received_at: string;
    /**
     * Next Expected At
     *
     * Timestamp when the next heartbeat is expected
     */
    next_expected_at: string;
};

/**
 * HeartbeatResponse
 *
 * Individual heartbeat record with detailed timing metrics
 */
export type HeartbeatResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Tcp Connect Ms
     */
    tcp_connect_ms?: number | null;
    /**
     * Tls Handshake Ms
     */
    tls_handshake_ms?: number | null;
    /**
     * Ttfb Ms
     */
    ttfb_ms?: number | null;
    /**
     * Timing Details
     */
    timing_details?: {
        [key: string]: unknown;
    } | null;
    /**
     * Step Results
     */
    step_results?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Is Anomaly
     */
    is_anomaly?: boolean;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * IncidentCreate
 */
export type IncidentCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Severity
     */
    severity: string;
    /**
     * Component Ids
     */
    component_ids?: Array<string>;
};

/**
 * IncidentDetailsResponse
 */
export type IncidentDetailsResponse = {
    incident: AppApiIncidentsIncidentResponse;
    /**
     * Heartbeats Count
     */
    heartbeats_count: number;
    /**
     * Affected Urls
     */
    affected_urls: Array<string>;
    /**
     * Primary Error
     */
    primary_error: string | null;
    /**
     * Recent Errors
     */
    recent_errors: Array<string>;
};

/**
 * IncidentUpdate
 */
export type IncidentUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Severity
     */
    severity?: string | null;
    /**
     * Component Ids
     */
    component_ids?: Array<string> | null;
};

/**
 * IncidentUpdateCreate
 */
export type IncidentUpdateCreate = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
};

/**
 * IncidentUpdateResponse
 */
export type IncidentUpdateResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Incident Id
     */
    incident_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MaintenanceCreate
 */
export type MaintenanceCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Scheduled Start
     */
    scheduled_start: string;
    /**
     * Scheduled End
     */
    scheduled_end: string;
    /**
     * Component Ids
     */
    component_ids?: Array<string>;
};

/**
 * MaintenanceResponse
 */
export type MaintenanceResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status Page Id
     */
    status_page_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Scheduled Start
     */
    scheduled_start: string;
    /**
     * Scheduled End
     */
    scheduled_end: string;
    /**
     * Actual Start
     */
    actual_start: string | null;
    /**
     * Actual End
     */
    actual_end: string | null;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Components
     */
    components?: Array<ComponentSummary>;
};

/**
 * MaintenanceUpdate
 */
export type MaintenanceUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Scheduled Start
     */
    scheduled_start?: string | null;
    /**
     * Scheduled End
     */
    scheduled_end?: string | null;
    /**
     * Actual Start
     */
    actual_start?: string | null;
    /**
     * Actual End
     */
    actual_end?: string | null;
    /**
     * Component Ids
     */
    component_ids?: Array<string> | null;
};

/**
 * MonitorCreate
 */
export type MonitorCreate = {
    /**
     * Url
     */
    url: string;
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Interval Seconds
     */
    interval_seconds?: number;
    /**
     * Monitor Type
     *
     * Monitor type
     */
    monitor_type?: 'simple' | 'scenario';
    /**
     * Steps
     *
     * Scenario steps (max 3, only for scenario type)
     */
    steps?: Array<ScenarioStep> | null;
};

/**
 * MonitorDetailResponse
 *
 * Detailed monitor information with heartbeat history
 */
export type MonitorDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Interval Seconds
     */
    interval_seconds: number;
    /**
     * Status
     */
    status: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Maintenance
     */
    is_maintenance?: boolean;
    /**
     * Last Checked
     */
    last_checked?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Monitor Type
     */
    monitor_type?: string;
    /**
     * Steps
     */
    steps?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Ssl Status
     */
    ssl_status?: string | null;
    /**
     * Ssl Expiry Date
     */
    ssl_expiry_date?: string | null;
    /**
     * Ssl Days Remaining
     */
    ssl_days_remaining?: number | null;
    /**
     * Domain Status
     */
    domain_status?: string | null;
    /**
     * Domain Expiry Date
     */
    domain_expiry_date?: string | null;
    /**
     * Domain Days Remaining
     */
    domain_days_remaining?: number | null;
    /**
     * Domain Last Checked
     */
    domain_last_checked?: string | null;
    /**
     * Last Ping Received
     *
     * Timestamp of last received heartbeat ping (heartbeat monitors only)
     */
    last_ping_received?: string | null;
    /**
     * Heartbeat Url
     *
     * URL to send heartbeat pings to (heartbeat monitors only)
     */
    heartbeat_url?: string | null;
    /**
     * Recent Heartbeats
     */
    recent_heartbeats?: Array<HeartbeatResponse>;
    /**
     * Uptime Percentage
     */
    uptime_percentage?: number | null;
    /**
     * Average Latency
     */
    average_latency?: number | null;
    /**
     * Total Checks
     */
    total_checks?: number;
};

/**
 * MonitorList
 */
export type MonitorList = {
    /**
     * Monitors
     */
    monitors: Array<MonitorResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
};

/**
 * MonitorResponse
 *
 * Basic monitor information without heartbeats
 */
export type MonitorResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Interval Seconds
     */
    interval_seconds: number;
    /**
     * Status
     */
    status: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Maintenance
     */
    is_maintenance?: boolean;
    /**
     * Last Checked
     */
    last_checked?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Monitor Type
     */
    monitor_type?: string;
    /**
     * Steps
     */
    steps?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Ssl Status
     */
    ssl_status?: string | null;
    /**
     * Ssl Expiry Date
     */
    ssl_expiry_date?: string | null;
    /**
     * Ssl Days Remaining
     */
    ssl_days_remaining?: number | null;
    /**
     * Domain Status
     */
    domain_status?: string | null;
    /**
     * Domain Expiry Date
     */
    domain_expiry_date?: string | null;
    /**
     * Domain Days Remaining
     */
    domain_days_remaining?: number | null;
    /**
     * Domain Last Checked
     */
    domain_last_checked?: string | null;
    /**
     * Last Ping Received
     *
     * Timestamp of last received heartbeat ping (heartbeat monitors only)
     */
    last_ping_received?: string | null;
    /**
     * Heartbeat Url
     *
     * URL to send heartbeat pings to (heartbeat monitors only)
     */
    heartbeat_url?: string | null;
};

/**
 * MonitorSummary
 */
export type MonitorSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Monitor Type
     */
    monitor_type: string;
};

/**
 * MonitorUpdate
 */
export type MonitorUpdate = {
    /**
     * Friendly Name
     */
    friendly_name?: string | null;
    /**
     * Interval Seconds
     */
    interval_seconds?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Maintenance
     */
    is_maintenance?: boolean | null;
};

/**
 * NotificationSettingsResponse
 */
export type NotificationSettingsResponse = {
    /**
     * Discord Webhook Url
     */
    discord_webhook_url?: string | null;
    /**
     * Discord Enabled
     */
    discord_enabled: boolean;
    /**
     * Slack Webhook Url
     */
    slack_webhook_url?: string | null;
    /**
     * Slack Enabled
     */
    slack_enabled: boolean;
    /**
     * Alert On Down
     */
    alert_on_down: boolean;
    /**
     * Alert On Recovery
     */
    alert_on_recovery: boolean;
    /**
     * Alert Threshold
     */
    alert_threshold: number;
    /**
     * Ssl Expiry Alert Days
     */
    ssl_expiry_alert_days: number;
    /**
     * Domain Expiry Alert Days
     */
    domain_expiry_alert_days: number;
};

/**
 * NotificationSettingsUpdate
 */
export type NotificationSettingsUpdate = {
    /**
     * Discord Webhook Url
     */
    discord_webhook_url?: string | null;
    /**
     * Discord Enabled
     */
    discord_enabled?: boolean | null;
    /**
     * Slack Webhook Url
     */
    slack_webhook_url?: string | null;
    /**
     * Slack Enabled
     */
    slack_enabled?: boolean | null;
    /**
     * Alert On Down
     */
    alert_on_down?: boolean | null;
    /**
     * Alert On Recovery
     */
    alert_on_recovery?: boolean | null;
    /**
     * Alert Threshold
     */
    alert_threshold?: number | null;
    /**
     * Ssl Expiry Alert Days
     */
    ssl_expiry_alert_days?: number | null;
    /**
     * Domain Expiry Alert Days
     */
    domain_expiry_alert_days?: number | null;
};

/**
 * PublicStatusPageResponse
 */
export type PublicStatusPageResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Slug
     */
    slug: string;
    /**
     * Show Uptime
     */
    show_uptime: boolean;
    /**
     * Show Incident History
     */
    show_incident_history: boolean;
    /**
     * Template
     */
    template: string;
    /**
     * Theme
     */
    theme: string;
    /**
     * Layout
     */
    layout: string;
    /**
     * Branding Logo Url
     */
    branding_logo_url: string | null;
    /**
     * Branding Primary Color
     */
    branding_primary_color: string | null;
    /**
     * Branding Custom Css
     */
    branding_custom_css: string | null;
    /**
     * Components
     */
    components?: Array<ComponentResponse>;
    /**
     * Active Incidents
     */
    active_incidents?: Array<AppSchemasStatusPageIncidentResponse>;
    /**
     * Upcoming Maintenances
     */
    upcoming_maintenances?: Array<MaintenanceResponse>;
    /**
     * Overall Status
     */
    overall_status?: string;
};

/**
 * PushToStatusPageRequest
 */
export type PushToStatusPageRequest = {
    /**
     * Status Page Id
     */
    status_page_id: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ResolveIncidentRequest
 */
export type ResolveIncidentRequest = {
    /**
     * Resolution Note
     */
    resolution_note?: string | null;
};

/**
 * ScenarioStep
 *
 * A single step in a scenario monitor
 */
export type ScenarioStep = {
    /**
     * Name
     *
     * Step name
     */
    name: string;
    /**
     * Url
     *
     * URL to check in this step
     */
    url: string;
    /**
     * Order
     *
     * Step order (1-3)
     */
    order: number;
    /**
     * Required Keyword
     *
     * Keyword that must appear in page content (case-insensitive)
     */
    required_keyword?: string | null;
};

/**
 * ShareAccessRequest
 *
 * Request model for accessing a password-protected shared monitor
 */
export type ShareAccessRequest = {
    /**
     * Password
     *
     * Password for protected share
     */
    password?: string | null;
};

/**
 * ShareAccessResponse
 *
 * Response model for share access validation
 */
export type ShareAccessResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Requires Password
     */
    requires_password?: boolean;
};

/**
 * ShareMonitorRequest
 *
 * Request model for enabling monitor sharing with expiration and password
 */
export type ShareMonitorRequest = {
    /**
     * Expires In Hours
     *
     * Hours until share expires (max 1 year)
     */
    expires_in_hours?: number | null;
    /**
     * Password
     *
     * Optional password to protect the share
     */
    password?: string | null;
};

/**
 * ShareMonitorResponse
 *
 * Response model for monitor sharing
 */
export type ShareMonitorResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Share Token
     */
    share_token: string;
    /**
     * Share Url
     */
    share_url: string;
    /**
     * Is Public
     */
    is_public: boolean;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Has Password
     */
    has_password?: boolean;
};

/**
 * StatusPageCreate
 */
export type StatusPageCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Custom Domain
     */
    custom_domain?: string | null;
    /**
     * Is Public
     */
    is_public?: boolean;
    /**
     * Show Uptime
     */
    show_uptime?: boolean;
    /**
     * Show Incident History
     */
    show_incident_history?: boolean;
    /**
     * Template
     */
    template?: string;
    /**
     * Theme
     */
    theme?: string;
    /**
     * Layout
     */
    layout?: string;
    /**
     * Branding Logo Url
     */
    branding_logo_url?: string | null;
    /**
     * Branding Primary Color
     */
    branding_primary_color?: string | null;
    /**
     * Branding Custom Css
     */
    branding_custom_css?: string | null;
    /**
     * Monitor Ids
     */
    monitor_ids?: Array<string>;
};

/**
 * StatusPageOption
 */
export type StatusPageOption = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * StatusPageResponse
 */
export type StatusPageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Custom Domain
     */
    custom_domain: string | null;
    /**
     * Is Public
     */
    is_public: boolean;
    /**
     * Show Uptime
     */
    show_uptime: boolean;
    /**
     * Show Incident History
     */
    show_incident_history: boolean;
    /**
     * Template
     */
    template: string;
    /**
     * Theme
     */
    theme: string;
    /**
     * Layout
     */
    layout: string;
    /**
     * Branding Logo Url
     */
    branding_logo_url: string | null;
    /**
     * Branding Primary Color
     */
    branding_primary_color: string | null;
    /**
     * Branding Custom Css
     */
    branding_custom_css: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * StatusPageUpdate
 */
export type StatusPageUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Custom Domain
     */
    custom_domain?: string | null;
    /**
     * Is Public
     */
    is_public?: boolean | null;
    /**
     * Show Uptime
     */
    show_uptime?: boolean | null;
    /**
     * Show Incident History
     */
    show_incident_history?: boolean | null;
    /**
     * Template
     */
    template?: string | null;
    /**
     * Theme
     */
    theme?: string | null;
    /**
     * Layout
     */
    layout?: string | null;
    /**
     * Branding Logo Url
     */
    branding_logo_url?: string | null;
    /**
     * Branding Primary Color
     */
    branding_primary_color?: string | null;
    /**
     * Branding Custom Css
     */
    branding_custom_css?: string | null;
};

/**
 * TestNotificationRequest
 */
export type TestNotificationRequest = {
    /**
     * Message
     */
    message?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * IncidentResponse
 */
export type AppApiIncidentsIncidentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Monitor Id
     */
    monitor_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Severity
     */
    severity: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Resolved At
     */
    resolved_at: string | null;
    /**
     * Total Downtime Seconds
     */
    total_downtime_seconds: number | null;
    /**
     * Affected Checks Count
     */
    affected_checks_count: number;
    /**
     * Root Cause Type
     */
    root_cause_type: string | null;
    /**
     * Root Cause Details
     */
    root_cause_details: {
        [key: string]: unknown;
    } | null;
    /**
     * Error Patterns
     */
    error_patterns: Array<string> | null;
    /**
     * Is Auto Created
     */
    is_auto_created: boolean;
    /**
     * Is Pushed To Status Page
     */
    is_pushed_to_status_page: boolean;
    /**
     * Duration Minutes
     */
    duration_minutes: number | null;
    /**
     * Is Ongoing
     */
    is_ongoing: boolean;
};

/**
 * IncidentResponse
 */
export type AppSchemasStatusPageIncidentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status Page Id
     */
    status_page_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Severity
     */
    severity: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Resolved At
     */
    resolved_at: string | null;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Updates
     */
    updates?: Array<IncidentUpdateResponse>;
    /**
     * Components
     */
    components?: Array<ComponentSummary>;
};

export type AuthInitAuthLoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthInitAuthLoginGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthCallbackAuthCallbackGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/callback';
};

export type AuthCallbackAuthCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentUserInfoAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserInfoAuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCurrentUserInfoAuthMeGetError = GetCurrentUserInfoAuthMeGetErrors[keyof GetCurrentUserInfoAuthMeGetErrors];

export type GetCurrentUserInfoAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListMonitorsMonitorsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/monitors/';
};

export type ListMonitorsMonitorsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMonitorsMonitorsGetError = ListMonitorsMonitorsGetErrors[keyof ListMonitorsMonitorsGetErrors];

export type ListMonitorsMonitorsGetResponses = {
    /**
     * Successful Response
     */
    200: MonitorList;
};

export type ListMonitorsMonitorsGetResponse = ListMonitorsMonitorsGetResponses[keyof ListMonitorsMonitorsGetResponses];

export type CreateMonitorMonitorsPostData = {
    body: MonitorCreate;
    path?: never;
    query?: never;
    url: '/monitors/';
};

export type CreateMonitorMonitorsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMonitorMonitorsPostError = CreateMonitorMonitorsPostErrors[keyof CreateMonitorMonitorsPostErrors];

export type CreateMonitorMonitorsPostResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type CreateMonitorMonitorsPostResponse = CreateMonitorMonitorsPostResponses[keyof CreateMonitorMonitorsPostResponses];

export type CreateHeartbeatMonitorMonitorsHeartbeatPostData = {
    body: HeartbeatMonitorCreate;
    path?: never;
    query?: never;
    url: '/monitors/heartbeat';
};

export type CreateHeartbeatMonitorMonitorsHeartbeatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateHeartbeatMonitorMonitorsHeartbeatPostError = CreateHeartbeatMonitorMonitorsHeartbeatPostErrors[keyof CreateHeartbeatMonitorMonitorsHeartbeatPostErrors];

export type CreateHeartbeatMonitorMonitorsHeartbeatPostResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type CreateHeartbeatMonitorMonitorsHeartbeatPostResponse = CreateHeartbeatMonitorMonitorsHeartbeatPostResponses[keyof CreateHeartbeatMonitorMonitorsHeartbeatPostResponses];

export type DeleteMonitorMonitorsMonitorIdDeleteData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}';
};

export type DeleteMonitorMonitorsMonitorIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMonitorMonitorsMonitorIdDeleteError = DeleteMonitorMonitorsMonitorIdDeleteErrors[keyof DeleteMonitorMonitorsMonitorIdDeleteErrors];

export type DeleteMonitorMonitorsMonitorIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMonitorMonitorsMonitorIdGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: {
        /**
         * Include Heartbeats
         *
         * Number of recent heartbeats to include
         */
        include_heartbeats?: number;
    };
    url: '/monitors/{monitor_id}';
};

export type GetMonitorMonitorsMonitorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorMonitorsMonitorIdGetError = GetMonitorMonitorsMonitorIdGetErrors[keyof GetMonitorMonitorsMonitorIdGetErrors];

export type GetMonitorMonitorsMonitorIdGetResponses = {
    /**
     * Successful Response
     */
    200: MonitorDetailResponse;
};

export type GetMonitorMonitorsMonitorIdGetResponse = GetMonitorMonitorsMonitorIdGetResponses[keyof GetMonitorMonitorsMonitorIdGetResponses];

export type UpdateMonitorMonitorsMonitorIdPutData = {
    body: MonitorUpdate;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}';
};

export type UpdateMonitorMonitorsMonitorIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMonitorMonitorsMonitorIdPutError = UpdateMonitorMonitorsMonitorIdPutErrors[keyof UpdateMonitorMonitorsMonitorIdPutErrors];

export type UpdateMonitorMonitorsMonitorIdPutResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type UpdateMonitorMonitorsMonitorIdPutResponse = UpdateMonitorMonitorsMonitorIdPutResponses[keyof UpdateMonitorMonitorsMonitorIdPutResponses];

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}/maintenance';
};

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteError = DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteErrors[keyof DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteErrors];

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteResponse = DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteResponses[keyof DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteResponses];

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}/maintenance';
};

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutError = EnableMaintenanceMonitorsMonitorIdMaintenancePutErrors[keyof EnableMaintenanceMonitorsMonitorIdMaintenancePutErrors];

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutResponse = EnableMaintenanceMonitorsMonitorIdMaintenancePutResponses[keyof EnableMaintenanceMonitorsMonitorIdMaintenancePutResponses];

export type GetMonitorStatsMonitorsMonitorIdStatsGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}/stats';
};

export type GetMonitorStatsMonitorsMonitorIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorStatsMonitorsMonitorIdStatsGetError = GetMonitorStatsMonitorsMonitorIdStatsGetErrors[keyof GetMonitorStatsMonitorsMonitorIdStatsGetErrors];

export type GetMonitorStatsMonitorsMonitorIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Number of heartbeats to return
         */
        limit?: number;
        /**
         * Offset
         *
         * Number of heartbeats to skip
         */
        offset?: number;
    };
    url: '/monitors/{monitor_id}/heartbeats';
};

export type GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetError = GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetErrors[keyof GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetErrors];

export type GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: {
        /**
         * Hours
         *
         * Hours to look back (max 1 week)
         */
        hours?: number;
    };
    url: '/monitors/{monitor_id}/timing-stats';
};

export type GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetError = GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetErrors[keyof GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetErrors];

export type GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DisableMonitorSharingMonitorsMonitorIdShareDeleteData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}/share';
};

export type DisableMonitorSharingMonitorsMonitorIdShareDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DisableMonitorSharingMonitorsMonitorIdShareDeleteError = DisableMonitorSharingMonitorsMonitorIdShareDeleteErrors[keyof DisableMonitorSharingMonitorsMonitorIdShareDeleteErrors];

export type DisableMonitorSharingMonitorsMonitorIdShareDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EnableMonitorSharingMonitorsMonitorIdSharePostData = {
    body: ShareMonitorRequest;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}/share';
};

export type EnableMonitorSharingMonitorsMonitorIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnableMonitorSharingMonitorsMonitorIdSharePostError = EnableMonitorSharingMonitorsMonitorIdSharePostErrors[keyof EnableMonitorSharingMonitorsMonitorIdSharePostErrors];

export type EnableMonitorSharingMonitorsMonitorIdSharePostResponses = {
    /**
     * Successful Response
     */
    200: ShareMonitorResponse;
};

export type EnableMonitorSharingMonitorsMonitorIdSharePostResponse = EnableMonitorSharingMonitorsMonitorIdSharePostResponses[keyof EnableMonitorSharingMonitorsMonitorIdSharePostResponses];

export type ValidateShareAccessMonitorsSharedShareTokenAccessPostData = {
    body: ShareAccessRequest;
    path: {
        /**
         * Share Token
         */
        share_token: string;
    };
    query?: never;
    url: '/monitors/shared/{share_token}/access';
};

export type ValidateShareAccessMonitorsSharedShareTokenAccessPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateShareAccessMonitorsSharedShareTokenAccessPostError = ValidateShareAccessMonitorsSharedShareTokenAccessPostErrors[keyof ValidateShareAccessMonitorsSharedShareTokenAccessPostErrors];

export type ValidateShareAccessMonitorsSharedShareTokenAccessPostResponses = {
    /**
     * Successful Response
     */
    200: ShareAccessResponse;
};

export type ValidateShareAccessMonitorsSharedShareTokenAccessPostResponse = ValidateShareAccessMonitorsSharedShareTokenAccessPostResponses[keyof ValidateShareAccessMonitorsSharedShareTokenAccessPostResponses];

export type GetSharedMonitorMonitorsSharedShareTokenGetData = {
    body?: never;
    path: {
        /**
         * Share Token
         */
        share_token: string;
    };
    query?: {
        /**
         * Password
         *
         * Password for protected shares
         */
        password?: string | null;
        /**
         * Include Heartbeats
         */
        include_heartbeats?: number;
    };
    url: '/monitors/shared/{share_token}';
};

export type GetSharedMonitorMonitorsSharedShareTokenGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSharedMonitorMonitorsSharedShareTokenGetError = GetSharedMonitorMonitorsSharedShareTokenGetErrors[keyof GetSharedMonitorMonitorsSharedShareTokenGetErrors];

export type GetSharedMonitorMonitorsSharedShareTokenGetResponses = {
    /**
     * Successful Response
     */
    200: MonitorDetailResponse;
};

export type GetSharedMonitorMonitorsSharedShareTokenGetResponse = GetSharedMonitorMonitorsSharedShareTokenGetResponses[keyof GetSharedMonitorMonitorsSharedShareTokenGetResponses];

export type GetPublicMonitorMonitorsPublicMonitorIdGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: {
        /**
         * Include Heartbeats
         */
        include_heartbeats?: number;
    };
    url: '/monitors/public/{monitor_id}';
};

export type GetPublicMonitorMonitorsPublicMonitorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublicMonitorMonitorsPublicMonitorIdGetError = GetPublicMonitorMonitorsPublicMonitorIdGetErrors[keyof GetPublicMonitorMonitorsPublicMonitorIdGetErrors];

export type GetPublicMonitorMonitorsPublicMonitorIdGetResponses = {
    /**
     * Successful Response
     */
    200: MonitorDetailResponse;
};

export type GetPublicMonitorMonitorsPublicMonitorIdGetResponse = GetPublicMonitorMonitorsPublicMonitorIdGetResponses[keyof GetPublicMonitorMonitorsPublicMonitorIdGetResponses];

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/api/heartbeats/{monitor_id}';
};

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetError = ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetErrors[keyof ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetErrors];

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetResponses = {
    /**
     * Successful Response
     */
    200: HeartbeatReceiveResponse;
};

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetResponse = ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetResponses[keyof ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetResponses];

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/api/heartbeats/{monitor_id}';
};

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostError = ReceiveHeartbeatApiHeartbeatsMonitorIdPostErrors[keyof ReceiveHeartbeatApiHeartbeatsMonitorIdPostErrors];

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostResponses = {
    /**
     * Successful Response
     */
    200: HeartbeatReceiveResponse;
};

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostResponse = ReceiveHeartbeatApiHeartbeatsMonitorIdPostResponses[keyof ReceiveHeartbeatApiHeartbeatsMonitorIdPostResponses];

export type GetSchedulerStatusStatusSchedulerGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/scheduler';
};

export type GetSchedulerStatusStatusSchedulerGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSchedulerStatusStatusSchedulerGetError = GetSchedulerStatusStatusSchedulerGetErrors[keyof GetSchedulerStatusStatusSchedulerGetErrors];

export type GetSchedulerStatusStatusSchedulerGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestDeepCheckStatusTestDeepGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
    };
    url: '/status/test-deep';
};

export type TestDeepCheckStatusTestDeepGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestDeepCheckStatusTestDeepGetError = TestDeepCheckStatusTestDeepGetErrors[keyof TestDeepCheckStatusTestDeepGetErrors];

export type TestDeepCheckStatusTestDeepGetResponses = {
    /**
     * Response Test Deep Check Status Test Deep Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TestDeepCheckStatusTestDeepGetResponse = TestDeepCheckStatusTestDeepGetResponses[keyof TestDeepCheckStatusTestDeepGetResponses];

export type TestSslCheckStatusTestSslGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
    };
    url: '/status/test-ssl';
};

export type TestSslCheckStatusTestSslGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestSslCheckStatusTestSslGetError = TestSslCheckStatusTestSslGetErrors[keyof TestSslCheckStatusTestSslGetErrors];

export type TestSslCheckStatusTestSslGetResponses = {
    /**
     * Response Test Ssl Check Status Test Ssl Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TestSslCheckStatusTestSslGetResponse = TestSslCheckStatusTestSslGetResponses[keyof TestSslCheckStatusTestSslGetResponses];

export type RefreshSchedulerStatusSchedulerRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/scheduler/refresh';
};

export type RefreshSchedulerStatusSchedulerRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshSchedulerStatusSchedulerRefreshPostError = RefreshSchedulerStatusSchedulerRefreshPostErrors[keyof RefreshSchedulerStatusSchedulerRefreshPostErrors];

export type RefreshSchedulerStatusSchedulerRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetNotificationSettingsApiNotificationsSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/settings';
};

export type GetNotificationSettingsApiNotificationsSettingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNotificationSettingsApiNotificationsSettingsGetError = GetNotificationSettingsApiNotificationsSettingsGetErrors[keyof GetNotificationSettingsApiNotificationsSettingsGetErrors];

export type GetNotificationSettingsApiNotificationsSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: NotificationSettingsResponse;
};

export type GetNotificationSettingsApiNotificationsSettingsGetResponse = GetNotificationSettingsApiNotificationsSettingsGetResponses[keyof GetNotificationSettingsApiNotificationsSettingsGetResponses];

export type UpdateNotificationSettingsApiNotificationsSettingsPutData = {
    body: NotificationSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/notifications/settings';
};

export type UpdateNotificationSettingsApiNotificationsSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNotificationSettingsApiNotificationsSettingsPutError = UpdateNotificationSettingsApiNotificationsSettingsPutErrors[keyof UpdateNotificationSettingsApiNotificationsSettingsPutErrors];

export type UpdateNotificationSettingsApiNotificationsSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: NotificationSettingsResponse;
};

export type UpdateNotificationSettingsApiNotificationsSettingsPutResponse = UpdateNotificationSettingsApiNotificationsSettingsPutResponses[keyof UpdateNotificationSettingsApiNotificationsSettingsPutResponses];

export type TestNotificationApiNotificationsTestPostData = {
    body: TestNotificationRequest;
    path?: never;
    query?: never;
    url: '/api/notifications/test';
};

export type TestNotificationApiNotificationsTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestNotificationApiNotificationsTestPostError = TestNotificationApiNotificationsTestPostErrors[keyof TestNotificationApiNotificationsTestPostErrors];

export type TestNotificationApiNotificationsTestPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListStatusPagesApiStatusPagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status-pages/';
};

export type ListStatusPagesApiStatusPagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListStatusPagesApiStatusPagesGetError = ListStatusPagesApiStatusPagesGetErrors[keyof ListStatusPagesApiStatusPagesGetErrors];

export type ListStatusPagesApiStatusPagesGetResponses = {
    /**
     * Response List Status Pages Api Status Pages  Get
     *
     * Successful Response
     */
    200: Array<StatusPageResponse>;
};

export type ListStatusPagesApiStatusPagesGetResponse = ListStatusPagesApiStatusPagesGetResponses[keyof ListStatusPagesApiStatusPagesGetResponses];

export type CreateStatusPageApiStatusPagesPostData = {
    body: StatusPageCreate;
    path?: never;
    query?: never;
    url: '/api/status-pages/';
};

export type CreateStatusPageApiStatusPagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStatusPageApiStatusPagesPostError = CreateStatusPageApiStatusPagesPostErrors[keyof CreateStatusPageApiStatusPagesPostErrors];

export type CreateStatusPageApiStatusPagesPostResponses = {
    /**
     * Successful Response
     */
    200: StatusPageResponse;
};

export type CreateStatusPageApiStatusPagesPostResponse = CreateStatusPageApiStatusPagesPostResponses[keyof CreateStatusPageApiStatusPagesPostResponses];

export type DeleteStatusPageApiStatusPagesStatusPageIdDeleteData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}';
};

export type DeleteStatusPageApiStatusPagesStatusPageIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStatusPageApiStatusPagesStatusPageIdDeleteError = DeleteStatusPageApiStatusPagesStatusPageIdDeleteErrors[keyof DeleteStatusPageApiStatusPagesStatusPageIdDeleteErrors];

export type DeleteStatusPageApiStatusPagesStatusPageIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStatusPageApiStatusPagesStatusPageIdGetData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}';
};

export type GetStatusPageApiStatusPagesStatusPageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStatusPageApiStatusPagesStatusPageIdGetError = GetStatusPageApiStatusPagesStatusPageIdGetErrors[keyof GetStatusPageApiStatusPagesStatusPageIdGetErrors];

export type GetStatusPageApiStatusPagesStatusPageIdGetResponses = {
    /**
     * Successful Response
     */
    200: StatusPageResponse;
};

export type GetStatusPageApiStatusPagesStatusPageIdGetResponse = GetStatusPageApiStatusPagesStatusPageIdGetResponses[keyof GetStatusPageApiStatusPagesStatusPageIdGetResponses];

export type UpdateStatusPageApiStatusPagesStatusPageIdPutData = {
    body: StatusPageUpdate;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}';
};

export type UpdateStatusPageApiStatusPagesStatusPageIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStatusPageApiStatusPagesStatusPageIdPutError = UpdateStatusPageApiStatusPagesStatusPageIdPutErrors[keyof UpdateStatusPageApiStatusPagesStatusPageIdPutErrors];

export type UpdateStatusPageApiStatusPagesStatusPageIdPutResponses = {
    /**
     * Successful Response
     */
    200: StatusPageResponse;
};

export type UpdateStatusPageApiStatusPagesStatusPageIdPutResponse = UpdateStatusPageApiStatusPagesStatusPageIdPutResponses[keyof UpdateStatusPageApiStatusPagesStatusPageIdPutResponses];

export type ListComponentsApiStatusPagesStatusPageIdComponentsGetData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/components';
};

export type ListComponentsApiStatusPagesStatusPageIdComponentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListComponentsApiStatusPagesStatusPageIdComponentsGetError = ListComponentsApiStatusPagesStatusPageIdComponentsGetErrors[keyof ListComponentsApiStatusPagesStatusPageIdComponentsGetErrors];

export type ListComponentsApiStatusPagesStatusPageIdComponentsGetResponses = {
    /**
     * Response List Components Api Status Pages  Status Page Id  Components Get
     *
     * Successful Response
     */
    200: Array<ComponentResponse>;
};

export type ListComponentsApiStatusPagesStatusPageIdComponentsGetResponse = ListComponentsApiStatusPagesStatusPageIdComponentsGetResponses[keyof ListComponentsApiStatusPagesStatusPageIdComponentsGetResponses];

export type CreateComponentApiStatusPagesStatusPageIdComponentsPostData = {
    body: ComponentCreate;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/components';
};

export type CreateComponentApiStatusPagesStatusPageIdComponentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateComponentApiStatusPagesStatusPageIdComponentsPostError = CreateComponentApiStatusPagesStatusPageIdComponentsPostErrors[keyof CreateComponentApiStatusPagesStatusPageIdComponentsPostErrors];

export type CreateComponentApiStatusPagesStatusPageIdComponentsPostResponses = {
    /**
     * Successful Response
     */
    200: ComponentResponse;
};

export type CreateComponentApiStatusPagesStatusPageIdComponentsPostResponse = CreateComponentApiStatusPagesStatusPageIdComponentsPostResponses[keyof CreateComponentApiStatusPagesStatusPageIdComponentsPostResponses];

export type DeleteComponentApiStatusPagesStatusPageIdComponentsComponentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
        /**
         * Component Id
         */
        component_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/components/{component_id}';
};

export type DeleteComponentApiStatusPagesStatusPageIdComponentsComponentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteComponentApiStatusPagesStatusPageIdComponentsComponentIdDeleteError = DeleteComponentApiStatusPagesStatusPageIdComponentsComponentIdDeleteErrors[keyof DeleteComponentApiStatusPagesStatusPageIdComponentsComponentIdDeleteErrors];

export type DeleteComponentApiStatusPagesStatusPageIdComponentsComponentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutData = {
    body: ComponentUpdate;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
        /**
         * Component Id
         */
        component_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/components/{component_id}';
};

export type UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutError = UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutErrors[keyof UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutErrors];

export type UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutResponses = {
    /**
     * Successful Response
     */
    200: ComponentResponse;
};

export type UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutResponse = UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutResponses[keyof UpdateComponentApiStatusPagesStatusPageIdComponentsComponentIdPutResponses];

export type ListIncidentsApiStatusPagesStatusPageIdIncidentsGetData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: {
        /**
         * Status
         */
        status?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/status-pages/{status_page_id}/incidents';
};

export type ListIncidentsApiStatusPagesStatusPageIdIncidentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListIncidentsApiStatusPagesStatusPageIdIncidentsGetError = ListIncidentsApiStatusPagesStatusPageIdIncidentsGetErrors[keyof ListIncidentsApiStatusPagesStatusPageIdIncidentsGetErrors];

export type ListIncidentsApiStatusPagesStatusPageIdIncidentsGetResponses = {
    /**
     * Response List Incidents Api Status Pages  Status Page Id  Incidents Get
     *
     * Successful Response
     */
    200: Array<AppSchemasStatusPageIncidentResponse>;
};

export type ListIncidentsApiStatusPagesStatusPageIdIncidentsGetResponse = ListIncidentsApiStatusPagesStatusPageIdIncidentsGetResponses[keyof ListIncidentsApiStatusPagesStatusPageIdIncidentsGetResponses];

export type CreateIncidentApiStatusPagesStatusPageIdIncidentsPostData = {
    body: IncidentCreate;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/incidents';
};

export type CreateIncidentApiStatusPagesStatusPageIdIncidentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateIncidentApiStatusPagesStatusPageIdIncidentsPostError = CreateIncidentApiStatusPagesStatusPageIdIncidentsPostErrors[keyof CreateIncidentApiStatusPagesStatusPageIdIncidentsPostErrors];

export type CreateIncidentApiStatusPagesStatusPageIdIncidentsPostResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasStatusPageIncidentResponse;
};

export type CreateIncidentApiStatusPagesStatusPageIdIncidentsPostResponse = CreateIncidentApiStatusPagesStatusPageIdIncidentsPostResponses[keyof CreateIncidentApiStatusPagesStatusPageIdIncidentsPostResponses];

export type DeleteIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
        /**
         * Incident Id
         */
        incident_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/incidents/{incident_id}';
};

export type DeleteIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdDeleteError = DeleteIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdDeleteErrors[keyof DeleteIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdDeleteErrors];

export type DeleteIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
        /**
         * Incident Id
         */
        incident_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/incidents/{incident_id}';
};

export type GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetError = GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetErrors[keyof GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetErrors];

export type GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasStatusPageIncidentResponse;
};

export type GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetResponse = GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetResponses[keyof GetIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdGetResponses];

export type UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutData = {
    body: IncidentUpdate;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
        /**
         * Incident Id
         */
        incident_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/incidents/{incident_id}';
};

export type UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutError = UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutErrors[keyof UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutErrors];

export type UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasStatusPageIncidentResponse;
};

export type UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutResponse = UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutResponses[keyof UpdateIncidentApiStatusPagesStatusPageIdIncidentsIncidentIdPutResponses];

export type AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostData = {
    body: IncidentUpdateCreate;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
        /**
         * Incident Id
         */
        incident_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/incidents/{incident_id}/updates';
};

export type AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostError = AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostErrors[keyof AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostErrors];

export type AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostResponses = {
    /**
     * Successful Response
     */
    200: IncidentUpdateResponse;
};

export type AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostResponse = AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostResponses[keyof AddIncidentUpdateApiStatusPagesStatusPageIdIncidentsIncidentIdUpdatesPostResponses];

export type ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: {
        /**
         * Status
         */
        status?: string | null;
        /**
         * Upcoming Only
         */
        upcoming_only?: boolean;
    };
    url: '/api/status-pages/{status_page_id}/maintenances';
};

export type ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetError = ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetErrors[keyof ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetErrors];

export type ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetResponses = {
    /**
     * Response List Maintenances Api Status Pages  Status Page Id  Maintenances Get
     *
     * Successful Response
     */
    200: Array<MaintenanceResponse>;
};

export type ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetResponse = ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetResponses[keyof ListMaintenancesApiStatusPagesStatusPageIdMaintenancesGetResponses];

export type CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostData = {
    body: MaintenanceCreate;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/maintenances';
};

export type CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostError = CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostErrors[keyof CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostErrors];

export type CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostResponses = {
    /**
     * Successful Response
     */
    200: MaintenanceResponse;
};

export type CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostResponse = CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostResponses[keyof CreateMaintenanceApiStatusPagesStatusPageIdMaintenancesPostResponses];

export type DeleteMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
        /**
         * Maintenance Id
         */
        maintenance_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/maintenances/{maintenance_id}';
};

export type DeleteMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdDeleteError = DeleteMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdDeleteErrors[keyof DeleteMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdDeleteErrors];

export type DeleteMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutData = {
    body: MaintenanceUpdate;
    path: {
        /**
         * Status Page Id
         */
        status_page_id: string;
        /**
         * Maintenance Id
         */
        maintenance_id: string;
    };
    query?: never;
    url: '/api/status-pages/{status_page_id}/maintenances/{maintenance_id}';
};

export type UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutError = UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutErrors[keyof UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutErrors];

export type UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutResponses = {
    /**
     * Successful Response
     */
    200: MaintenanceResponse;
};

export type UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutResponse = UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutResponses[keyof UpdateMaintenanceApiStatusPagesStatusPageIdMaintenancesMaintenanceIdPutResponses];

export type GetPublicStatusPageApiStatusPagesPublicSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/status-pages/public/{slug}';
};

export type GetPublicStatusPageApiStatusPagesPublicSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublicStatusPageApiStatusPagesPublicSlugGetError = GetPublicStatusPageApiStatusPagesPublicSlugGetErrors[keyof GetPublicStatusPageApiStatusPagesPublicSlugGetErrors];

export type GetPublicStatusPageApiStatusPagesPublicSlugGetResponses = {
    /**
     * Successful Response
     */
    200: PublicStatusPageResponse;
};

export type GetPublicStatusPageApiStatusPagesPublicSlugGetResponse = GetPublicStatusPageApiStatusPagesPublicSlugGetResponses[keyof GetPublicStatusPageApiStatusPagesPublicSlugGetResponses];

export type GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Include Resolved
         */
        include_resolved?: boolean;
    };
    url: '/api/monitors/{monitor_id}/incidents';
};

export type GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetError = GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetErrors[keyof GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetErrors];

export type GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetResponses = {
    /**
     * Response Get Monitor Incidents Api Monitors  Monitor Id  Incidents Get
     *
     * Successful Response
     */
    200: Array<AppApiIncidentsIncidentResponse>;
};

export type GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetResponse = GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetResponses[keyof GetMonitorIncidentsApiMonitorsMonitorIdIncidentsGetResponses];

export type GetIncidentDetailsApiIncidentsIncidentIdGetData = {
    body?: never;
    path: {
        /**
         * Incident Id
         */
        incident_id: string;
    };
    query?: never;
    url: '/api/incidents/{incident_id}';
};

export type GetIncidentDetailsApiIncidentsIncidentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIncidentDetailsApiIncidentsIncidentIdGetError = GetIncidentDetailsApiIncidentsIncidentIdGetErrors[keyof GetIncidentDetailsApiIncidentsIncidentIdGetErrors];

export type GetIncidentDetailsApiIncidentsIncidentIdGetResponses = {
    /**
     * Successful Response
     */
    200: IncidentDetailsResponse;
};

export type GetIncidentDetailsApiIncidentsIncidentIdGetResponse = GetIncidentDetailsApiIncidentsIncidentIdGetResponses[keyof GetIncidentDetailsApiIncidentsIncidentIdGetResponses];

export type ResolveIncidentApiIncidentsIncidentIdResolvePostData = {
    body: ResolveIncidentRequest;
    path: {
        /**
         * Incident Id
         */
        incident_id: string;
    };
    query?: never;
    url: '/api/incidents/{incident_id}/resolve';
};

export type ResolveIncidentApiIncidentsIncidentIdResolvePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolveIncidentApiIncidentsIncidentIdResolvePostError = ResolveIncidentApiIncidentsIncidentIdResolvePostErrors[keyof ResolveIncidentApiIncidentsIncidentIdResolvePostErrors];

export type ResolveIncidentApiIncidentsIncidentIdResolvePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/api/monitors/{monitor_id}/status-page-options';
};

export type GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetError = GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetErrors[keyof GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetErrors];

export type GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetResponses = {
    /**
     * Response Get Status Page Options Api Monitors  Monitor Id  Status Page Options Get
     *
     * Successful Response
     */
    200: Array<StatusPageOption>;
};

export type GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetResponse = GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetResponses[keyof GetStatusPageOptionsApiMonitorsMonitorIdStatusPageOptionsGetResponses];

export type PushIncidentToStatusPageApiIncidentsIncidentIdPushToStatusPagePostData = {
    body: PushToStatusPageRequest;
    path: {
        /**
         * Incident Id
         */
        incident_id: string;
    };
    query?: never;
    url: '/api/incidents/{incident_id}/push-to-status-page';
};

export type PushIncidentToStatusPageApiIncidentsIncidentIdPushToStatusPagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PushIncidentToStatusPageApiIncidentsIncidentIdPushToStatusPagePostError = PushIncidentToStatusPageApiIncidentsIncidentIdPushToStatusPagePostErrors[keyof PushIncidentToStatusPageApiIncidentsIncidentIdPushToStatusPagePostErrors];

export type PushIncidentToStatusPageApiIncidentsIncidentIdPushToStatusPagePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProcessMonitorIncidentsApiMonitorsMonitorIdProcessIncidentsPostData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/api/monitors/{monitor_id}/process-incidents';
};

export type ProcessMonitorIncidentsApiMonitorsMonitorIdProcessIncidentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessMonitorIncidentsApiMonitorsMonitorIdProcessIncidentsPostError = ProcessMonitorIncidentsApiMonitorsMonitorIdProcessIncidentsPostErrors[keyof ProcessMonitorIncidentsApiMonitorsMonitorIdProcessIncidentsPostErrors];

export type ProcessMonitorIncidentsApiMonitorsMonitorIdProcessIncidentsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadUsersMeUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ReadUsersMeUsersMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersMeUsersMeGetError = ReadUsersMeUsersMeGetErrors[keyof ReadUsersMeUsersMeGetErrors];

export type ReadUsersMeUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
