// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeartbeatMonitorCreate
 *
 * Request model for creating heartbeat monitor
 */
export type HeartbeatMonitorCreate = {
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Interval Seconds
     *
     * How often heartbeat is expected (minimum 60 seconds)
     */
    interval_seconds: number;
    /**
     * Monitor Type
     *
     * Monitor type (must be heartbeat)
     */
    monitor_type?: 'heartbeat';
};

/**
 * HeartbeatReceiveResponse
 *
 * Response when heartbeat ping is received
 */
export type HeartbeatReceiveResponse = {
    /**
     * Success
     *
     * Whether the heartbeat was successfully received
     */
    success: boolean;
    /**
     * Message
     *
     * Human-readable message about the heartbeat reception
     */
    message: string;
    /**
     * Monitor Id
     *
     * ID of the monitor that received the heartbeat
     */
    monitor_id: string;
    /**
     * Received At
     *
     * Timestamp when the heartbeat was received
     */
    received_at: string;
    /**
     * Next Expected At
     *
     * Timestamp when the next heartbeat is expected
     */
    next_expected_at: string;
};

/**
 * HeartbeatResponse
 *
 * Individual heartbeat record with detailed timing metrics
 */
export type HeartbeatResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Status Code
     */
    status_code: number;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Tcp Connect Ms
     */
    tcp_connect_ms?: number | null;
    /**
     * Tls Handshake Ms
     */
    tls_handshake_ms?: number | null;
    /**
     * Ttfb Ms
     */
    ttfb_ms?: number | null;
    /**
     * Timing Details
     */
    timing_details?: {
        [key: string]: unknown;
    } | null;
    /**
     * Step Results
     */
    step_results?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Is Anomaly
     */
    is_anomaly?: boolean;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MonitorCreate
 */
export type MonitorCreate = {
    /**
     * Url
     */
    url: string;
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Interval Seconds
     */
    interval_seconds?: number;
    /**
     * Monitor Type
     *
     * Monitor type
     */
    monitor_type?: 'simple' | 'scenario';
    /**
     * Steps
     *
     * Scenario steps (max 3, only for scenario type)
     */
    steps?: Array<ScenarioStep> | null;
};

/**
 * MonitorDetailResponse
 *
 * Detailed monitor information with heartbeat history
 */
export type MonitorDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Interval Seconds
     */
    interval_seconds: number;
    /**
     * Status
     */
    status: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Maintenance
     */
    is_maintenance?: boolean;
    /**
     * Last Checked
     */
    last_checked?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Monitor Type
     */
    monitor_type?: string;
    /**
     * Steps
     */
    steps?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Ssl Status
     */
    ssl_status?: string | null;
    /**
     * Ssl Expiry Date
     */
    ssl_expiry_date?: string | null;
    /**
     * Ssl Days Remaining
     */
    ssl_days_remaining?: number | null;
    /**
     * Domain Status
     */
    domain_status?: string | null;
    /**
     * Domain Expiry Date
     */
    domain_expiry_date?: string | null;
    /**
     * Domain Days Remaining
     */
    domain_days_remaining?: number | null;
    /**
     * Domain Last Checked
     */
    domain_last_checked?: string | null;
    /**
     * Last Ping Received
     *
     * Timestamp of last received heartbeat ping (heartbeat monitors only)
     */
    last_ping_received?: string | null;
    /**
     * Heartbeat Url
     *
     * URL to send heartbeat pings to (heartbeat monitors only)
     */
    heartbeat_url?: string | null;
    /**
     * Recent Heartbeats
     */
    recent_heartbeats?: Array<HeartbeatResponse>;
    /**
     * Uptime Percentage
     */
    uptime_percentage?: number | null;
    /**
     * Average Latency
     */
    average_latency?: number | null;
    /**
     * Total Checks
     */
    total_checks?: number;
};

/**
 * MonitorList
 */
export type MonitorList = {
    /**
     * Monitors
     */
    monitors: Array<MonitorResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
};

/**
 * MonitorResponse
 *
 * Basic monitor information without heartbeats
 */
export type MonitorResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Friendly Name
     */
    friendly_name: string;
    /**
     * Interval Seconds
     */
    interval_seconds: number;
    /**
     * Status
     */
    status: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Maintenance
     */
    is_maintenance?: boolean;
    /**
     * Last Checked
     */
    last_checked?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Monitor Type
     */
    monitor_type?: string;
    /**
     * Steps
     */
    steps?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Ssl Status
     */
    ssl_status?: string | null;
    /**
     * Ssl Expiry Date
     */
    ssl_expiry_date?: string | null;
    /**
     * Ssl Days Remaining
     */
    ssl_days_remaining?: number | null;
    /**
     * Domain Status
     */
    domain_status?: string | null;
    /**
     * Domain Expiry Date
     */
    domain_expiry_date?: string | null;
    /**
     * Domain Days Remaining
     */
    domain_days_remaining?: number | null;
    /**
     * Domain Last Checked
     */
    domain_last_checked?: string | null;
    /**
     * Last Ping Received
     *
     * Timestamp of last received heartbeat ping (heartbeat monitors only)
     */
    last_ping_received?: string | null;
    /**
     * Heartbeat Url
     *
     * URL to send heartbeat pings to (heartbeat monitors only)
     */
    heartbeat_url?: string | null;
};

/**
 * MonitorUpdate
 */
export type MonitorUpdate = {
    /**
     * Friendly Name
     */
    friendly_name?: string | null;
    /**
     * Interval Seconds
     */
    interval_seconds?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Maintenance
     */
    is_maintenance?: boolean | null;
};

/**
 * ScenarioStep
 *
 * A single step in a scenario monitor
 */
export type ScenarioStep = {
    /**
     * Name
     *
     * Step name
     */
    name: string;
    /**
     * Url
     *
     * URL to check in this step
     */
    url: string;
    /**
     * Order
     *
     * Step order (1-3)
     */
    order: number;
    /**
     * Required Keyword
     *
     * Keyword that must appear in page content (case-insensitive)
     */
    required_keyword?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthInitAuthLoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthInitAuthLoginGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthCallbackAuthCallbackGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/callback';
};

export type AuthCallbackAuthCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentUserInfoAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserInfoAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProtectedRouteAuthProtectedGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/protected';
};

export type ProtectedRouteAuthProtectedGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateTokenForTestingAuthTokenPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
    };
    url: '/auth/token';
};

export type CreateTokenForTestingAuthTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTokenForTestingAuthTokenPostError = CreateTokenForTestingAuthTokenPostErrors[keyof CreateTokenForTestingAuthTokenPostErrors];

export type CreateTokenForTestingAuthTokenPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListMonitorsMonitorsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/monitors/';
};

export type ListMonitorsMonitorsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMonitorsMonitorsGetError = ListMonitorsMonitorsGetErrors[keyof ListMonitorsMonitorsGetErrors];

export type ListMonitorsMonitorsGetResponses = {
    /**
     * Successful Response
     */
    200: MonitorList;
};

export type ListMonitorsMonitorsGetResponse = ListMonitorsMonitorsGetResponses[keyof ListMonitorsMonitorsGetResponses];

export type CreateMonitorMonitorsPostData = {
    body: MonitorCreate;
    path?: never;
    query?: never;
    url: '/monitors/';
};

export type CreateMonitorMonitorsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMonitorMonitorsPostError = CreateMonitorMonitorsPostErrors[keyof CreateMonitorMonitorsPostErrors];

export type CreateMonitorMonitorsPostResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type CreateMonitorMonitorsPostResponse = CreateMonitorMonitorsPostResponses[keyof CreateMonitorMonitorsPostResponses];

export type CreateHeartbeatMonitorMonitorsHeartbeatPostData = {
    body: HeartbeatMonitorCreate;
    path?: never;
    query?: never;
    url: '/monitors/heartbeat';
};

export type CreateHeartbeatMonitorMonitorsHeartbeatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateHeartbeatMonitorMonitorsHeartbeatPostError = CreateHeartbeatMonitorMonitorsHeartbeatPostErrors[keyof CreateHeartbeatMonitorMonitorsHeartbeatPostErrors];

export type CreateHeartbeatMonitorMonitorsHeartbeatPostResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type CreateHeartbeatMonitorMonitorsHeartbeatPostResponse = CreateHeartbeatMonitorMonitorsHeartbeatPostResponses[keyof CreateHeartbeatMonitorMonitorsHeartbeatPostResponses];

export type DeleteMonitorMonitorsMonitorIdDeleteData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}';
};

export type DeleteMonitorMonitorsMonitorIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMonitorMonitorsMonitorIdDeleteError = DeleteMonitorMonitorsMonitorIdDeleteErrors[keyof DeleteMonitorMonitorsMonitorIdDeleteErrors];

export type DeleteMonitorMonitorsMonitorIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMonitorMonitorsMonitorIdGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: {
        /**
         * Include Heartbeats
         *
         * Number of recent heartbeats to include
         */
        include_heartbeats?: number;
    };
    url: '/monitors/{monitor_id}';
};

export type GetMonitorMonitorsMonitorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorMonitorsMonitorIdGetError = GetMonitorMonitorsMonitorIdGetErrors[keyof GetMonitorMonitorsMonitorIdGetErrors];

export type GetMonitorMonitorsMonitorIdGetResponses = {
    /**
     * Successful Response
     */
    200: MonitorDetailResponse;
};

export type GetMonitorMonitorsMonitorIdGetResponse = GetMonitorMonitorsMonitorIdGetResponses[keyof GetMonitorMonitorsMonitorIdGetResponses];

export type UpdateMonitorMonitorsMonitorIdPutData = {
    body: MonitorUpdate;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}';
};

export type UpdateMonitorMonitorsMonitorIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMonitorMonitorsMonitorIdPutError = UpdateMonitorMonitorsMonitorIdPutErrors[keyof UpdateMonitorMonitorsMonitorIdPutErrors];

export type UpdateMonitorMonitorsMonitorIdPutResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type UpdateMonitorMonitorsMonitorIdPutResponse = UpdateMonitorMonitorsMonitorIdPutResponses[keyof UpdateMonitorMonitorsMonitorIdPutResponses];

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}/maintenance';
};

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteError = DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteErrors[keyof DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteErrors];

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteResponse = DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteResponses[keyof DisableMaintenanceMonitorsMonitorIdMaintenanceDeleteResponses];

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}/maintenance';
};

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutError = EnableMaintenanceMonitorsMonitorIdMaintenancePutErrors[keyof EnableMaintenanceMonitorsMonitorIdMaintenancePutErrors];

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutResponses = {
    /**
     * Successful Response
     */
    200: MonitorResponse;
};

export type EnableMaintenanceMonitorsMonitorIdMaintenancePutResponse = EnableMaintenanceMonitorsMonitorIdMaintenancePutResponses[keyof EnableMaintenanceMonitorsMonitorIdMaintenancePutResponses];

export type GetMonitorStatsMonitorsMonitorIdStatsGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/monitors/{monitor_id}/stats';
};

export type GetMonitorStatsMonitorsMonitorIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorStatsMonitorsMonitorIdStatsGetError = GetMonitorStatsMonitorsMonitorIdStatsGetErrors[keyof GetMonitorStatsMonitorsMonitorIdStatsGetErrors];

export type GetMonitorStatsMonitorsMonitorIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Number of heartbeats to return
         */
        limit?: number;
        /**
         * Offset
         *
         * Number of heartbeats to skip
         */
        offset?: number;
    };
    url: '/monitors/{monitor_id}/heartbeats';
};

export type GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetError = GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetErrors[keyof GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetErrors];

export type GetMonitorHeartbeatsMonitorsMonitorIdHeartbeatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: {
        /**
         * Hours
         *
         * Hours to look back (max 1 week)
         */
        hours?: number;
    };
    url: '/monitors/{monitor_id}/timing-stats';
};

export type GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetError = GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetErrors[keyof GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetErrors];

export type GetMonitorTimingStatsMonitorsMonitorIdTimingStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/api/heartbeats/{monitor_id}';
};

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetError = ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetErrors[keyof ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetErrors];

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetResponses = {
    /**
     * Successful Response
     */
    200: HeartbeatReceiveResponse;
};

export type ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetResponse = ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetResponses[keyof ReceiveHeartbeatGetApiHeartbeatsMonitorIdGetResponses];

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostData = {
    body?: never;
    path: {
        /**
         * Monitor Id
         */
        monitor_id: string;
    };
    query?: never;
    url: '/api/heartbeats/{monitor_id}';
};

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostError = ReceiveHeartbeatApiHeartbeatsMonitorIdPostErrors[keyof ReceiveHeartbeatApiHeartbeatsMonitorIdPostErrors];

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostResponses = {
    /**
     * Successful Response
     */
    200: HeartbeatReceiveResponse;
};

export type ReceiveHeartbeatApiHeartbeatsMonitorIdPostResponse = ReceiveHeartbeatApiHeartbeatsMonitorIdPostResponses[keyof ReceiveHeartbeatApiHeartbeatsMonitorIdPostResponses];

export type GetSchedulerStatusStatusSchedulerGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/scheduler';
};

export type GetSchedulerStatusStatusSchedulerGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestDeepCheckStatusTestDeepGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
    };
    url: '/status/test-deep';
};

export type TestDeepCheckStatusTestDeepGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestDeepCheckStatusTestDeepGetError = TestDeepCheckStatusTestDeepGetErrors[keyof TestDeepCheckStatusTestDeepGetErrors];

export type TestDeepCheckStatusTestDeepGetResponses = {
    /**
     * Response Test Deep Check Status Test Deep Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TestDeepCheckStatusTestDeepGetResponse = TestDeepCheckStatusTestDeepGetResponses[keyof TestDeepCheckStatusTestDeepGetResponses];

export type TestSslCheckStatusTestSslGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
    };
    url: '/status/test-ssl';
};

export type TestSslCheckStatusTestSslGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestSslCheckStatusTestSslGetError = TestSslCheckStatusTestSslGetErrors[keyof TestSslCheckStatusTestSslGetErrors];

export type TestSslCheckStatusTestSslGetResponses = {
    /**
     * Response Test Ssl Check Status Test Ssl Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TestSslCheckStatusTestSslGetResponse = TestSslCheckStatusTestSslGetResponses[keyof TestSslCheckStatusTestSslGetResponses];

export type RefreshSchedulerStatusSchedulerRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status/scheduler/refresh';
};

export type RefreshSchedulerStatusSchedulerRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadUsersMeUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ReadUsersMeUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
